name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - run: npm ci
      - run: npm run build
  preview:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.preview.outputs.url }}
    steps:
      - name: wait
        id: preview
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID  }}
          project: ${{ secrets.CLOUDFLARE_PROJECT }}
  lighthouse:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: preview
    steps:
      # checkout need to upload artifacts with hash from git
      - uses: actions/checkout@v1
        with:
          lfs: true 
      - uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{ needs.preview.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
  broken-link-checker:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - uses: celinekurpershoek/link-checker@v1.0.2
        with:
          url: ${{ needs.preview.outputs.url }}
          honorRobotExclusions: false
          recursiveLinks: true
